FROM golang:1.10 AS BUILD

WORKDIR /go/src/app
COPY ./server ./

RUN go get -v -d .

RUN CGO_ENABLED=0 GOOS=linux go build -a oklogging-server.go

FROM alpine

COPY --from=BUILD /go/src/app/oklogging-server /

CMD ["/oklogging-server"]
